// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/account/orders" | "/account/orders/[id]" | "/account/profile" | "/admin/analytics" | "/admin/customers" | "/admin/dashboard" | "/admin/orders" | "/admin/products" | "/admin/products/[id]" | "/admin/products/new" | "/admin/promotions" | "/admin/settings" | "/cart" | "/checkout" | "/contact-us" | "/faq" | "/forgot-password" | "/login" | "/privacy" | "/reset-password" | "/shipping-and-returns" | "/shop/[category]" | "/shop/product/[slug]" | "/signup" | "/store-policy" | "/terms" | "/wishlist"
type AppRouteHandlerRoutes = "/api/contact" | "/api/currency/rates" | "/api/order-status-email" | "/api/upload" | "/api/verify-payment" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/" | "/account"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/account/orders": {}
  "/account/orders/[id]": { "id": string; }
  "/account/profile": {}
  "/admin/analytics": {}
  "/admin/customers": {}
  "/admin/dashboard": {}
  "/admin/orders": {}
  "/admin/products": {}
  "/admin/products/[id]": { "id": string; }
  "/admin/products/new": {}
  "/admin/promotions": {}
  "/admin/settings": {}
  "/api/contact": {}
  "/api/currency/rates": {}
  "/api/order-status-email": {}
  "/api/upload": {}
  "/api/verify-payment": {}
  "/auth/callback": {}
  "/cart": {}
  "/checkout": {}
  "/contact-us": {}
  "/faq": {}
  "/forgot-password": {}
  "/login": {}
  "/privacy": {}
  "/reset-password": {}
  "/shipping-and-returns": {}
  "/shop/[category]": { "category": string; }
  "/shop/product/[slug]": { "slug": string; }
  "/signup": {}
  "/store-policy": {}
  "/terms": {}
  "/wishlist": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/account": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
